# Generated by Django 5.2.7 on 2026-01-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nif',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='morada',
            field=models.TextField(verbose_name='Endereço'),
        ),
    ]
